# Generated by Django 5.0.1 on 2024-01-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('image', models.ImageField(null=True, upload_to='staticfiles', verbose_name='Изображение')),
                ('table', models.FileField(max_length=3000, null=True, upload_to='', verbose_name='Таблица')),
            ],
            options={
                'verbose_name': 'Востребованность',
                'verbose_name_plural': 'Востребованности',
                'db_table': 'demand',
            },
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('image', models.ImageField(null=True, upload_to='staticfiles', verbose_name='Изображение')),
                ('table', models.FileField(max_length=3000, null=True, upload_to='', verbose_name='Таблица')),
            ],
            options={
                'verbose_name': 'География',
                'verbose_name_plural': 'География',
                'db_table': 'geography',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('image', models.ImageField(null=True, upload_to='staticfiles', verbose_name='Изображение')),
                ('table', models.FileField(max_length=3000, null=True, upload_to='', verbose_name='Таблица')),
            ],
            options={
                'verbose_name': 'Навыки',
                'verbose_name_plural': 'Навыки',
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание')),
                ('skills', models.CharField(max_length=255, verbose_name='Навыки')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('salary', models.CharField(max_length=25, verbose_name='Зарплата')),
                ('area_name', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('published_at', models.TextField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'db_table': 'vacancies',
            },
        ),
    ]
