# Generated by Django 5.0.1 on 2024-01-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulearn', '0002_demand_geography'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='table',
            field=models.FileField(max_length=3000, null=True, upload_to='', verbose_name='Таблица'),
        ),
        migrations.AddField(
            model_name='geography',
            name='table',
            field=models.FileField(max_length=3000, null=True, upload_to='', verbose_name='Таблица'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='image',
            field=models.ImageField(null=True, upload_to='staticfiles/img', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='geography',
            name='image',
            field=models.ImageField(null=True, upload_to='staticfiles/img', verbose_name='Изображение'),
        ),
    ]
