# Generated by Django 5.0.1 on 2024-01-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulearn', '0004_alter_demand_image_alter_geography_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='image',
            field=models.ImageField(null=True, upload_to='staticfiles', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='geography',
            name='image',
            field=models.ImageField(null=True, upload_to='staticfiles', verbose_name='Изображение'),
        ),
    ]
