# Generated by Django 5.0.1 on 2024-01-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulearn', '0005_alter_demand_image_alter_geography_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='geography',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
