# Generated by Django 5.0.1 on 2024-01-16 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ulearn', '0006_demand_title_geography_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteUser',
        ),
    ]
